version: '3.9'

services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  server:
    image: ajitjivane001/mini-blog-server:latest
    restart: unless-stopped
    ports:
      - '5000:5000'
    environment:
      MONGO_URI: mongodb://mongo:27017/miniblog
      CORS_ORIGIN: http://client
    depends_on:
      - mongo

  client:
    image: ajitjivane001/mini-blog-client:latest
    restart: unless-stopped
    ports:
      - '3000:80'
    depends_on:
      - server

volumes:
  mongo-data:
